FROM condaforge/miniforge3

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        wget \
        curl \
        git \
        libtbb-dev \
        libgl1-mesa-dev \
	&& apt-get clean

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ENV PATH /opt/conda/bin:$PATH

# By default running container starts bash shell
CMD [ "/bin/bash" ]
RUN mamba update -n base --all -y
RUN mamba install python=3.12
# Pick any of the 3 mosdef repos
RUN git clone https://github.com/mosdef-hub/foyer.git
RUN mamba env update -n base -f foyer/environment-dev.yml
RUN pip install -e foyer 
RUN mamba install py3Dmol nglview openbabel jupyter 

# Make RUN commands use `bash --login`: -- fixes conda init
# https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["/bin/bash", "--login", "-c"]

# Prevent python from loading packages from outside the container
# default empty pythonpath
ENV PYTHONPATH=/ignore/pythonpath
ENV PYTHONUSERBASE=/ignore/pythonpath
