FROM chrisjonesbsu/cpuconda:latest

RUN git clone https://github.com/mosdef-hub/mbuild.git
RUN mamba env update -f mbuid/environment-dev.yml
RUN pip install -e mbuild 
RUN mamba install py3Dmol nglview openbabel 
