FROM condaforge/miniforge3

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
        git \
		libxml2-dev \
	&& apt-get clean

# Install miniforge
ENV LANG C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

# By default running container starts bash shell
CMD [ "/bin/bash" ]
RUN mamba update -n base --all -y && \
	mamba install cassandra=1.3.1 mbuild=1.3.1 signac signac-flow row foyer=1.1 gmso=0.15 py3Dmol nglview jupyter python=3.13 -y

# Make RUN commands use `bash --login`: -- fixes conda init
# https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["/bin/bash", "--login", "-c"]

# Prevent python from loading packages from outside the container
# default empty pythonpath
ENV PYTHONPATH /ignore/pythonpath
ENV PYTHONUSERBASE /ignore/pythonpath
