FROM docker.io/library/ubuntu:24.04

# Install dependencies
RUN apt-get update && apt-get install -y wget cmake g++ gcc git libeigen3-dev libjpeg-dev libpng-dev openmpi-bin libopenmpi-dev 

# Install miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O Miniforge3.sh && \
    bash Miniforge3.sh -b -p /opt/miniforge3 && \
    rm Miniforge3.sh

ENV PATH="/opt/miniforge3/bin:${PATH}"
ENV PATH=/usr/local/cuda-12.2/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:$LD_LIBRARY_PATH
ENV CC=gcc
ENV CXX=g++
ENV CONDA_PREFIX=/opt/miniforge3

# Install MoSDeF software and compile LAMMPS
CMD [ "/bin/bash" ]
RUN conda init bash && \
    echo "conda activate base" >> ~/.bashrc && \
    conda update -n base --all -y && \ 
    conda install -n base cmake=3.28 python=3.12 -y && \
	git clone https://github.com/gromacs/gromacs.git && \
    cd gromacs && \
    mkdir build && \
    cd build && \
	cmake .. \ 
		  -DGMX_BUILD_OWN_FFTW=ON \
		  -DGMX_GPU=OFF \
		  -DGMX_DOUBLE=ON \
		  -DGMX_MPI=ON \
		  -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
		  -DCMAKE_BUILD_TYPE=Release && \
	make && \
	make install 

SHELL ["/bin/bash", "--login", "-c"]
