name: build_gpuconda

on:
  push:
    branches: [ main ]
    # Run when container is changed
    paths:
        - 'base/dockerfile_gpuconda'
  # Allows workflow to be manually triggered
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gpuconda

jobs:
  build_gpuconda:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./base/dockerfile_gpuconda
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
